language: android

android:
  components:
  - android-28
  - extra-android-m2repository

  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

  script:
  - ./gradlew assembleDebug