language: android

android:
  components:
  - tools
  - build-tools-28.0.3
  - android-28
  - extra-android-m2repository

  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+


  before_install:
  - yes | sdkmanager "platforms;android-28"

  script:
  - ./gradlew assembleDebug
  - ./gradlew jacocoTestReport coveralls
